name: hallaq_dz
description: "A premium Barber App developed by ISKANDER KHANTOUCHE."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.1
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  firebase_messaging: ^15.2.10
  google_sign_in: ^6.2.1
  http: ^1.2.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
